### ISSUE TITLE
Lexical-based alternative?

### ISSUE THREAD

**Issue by dead-claudia** [tc39/proposal-await-dictionary#20]
Maybe something like `await let foo = bar`, where `foo` is implicitly `await`ed on first evaluation or (awkward to spec, easy to implement) function closure reference.

```
await let foo = one()
await let bar = two(2)
// No suspension yet

let baz = foo /* suspend */ + 1
let wat = foo /* no suspend */ + bar /* suspend */
```

This sidesteps the whole object API ergonomics problem.

**Comment by ljharb** [comment]
That is a definite nonstarter, as many delegates have previously objected to async interleaving points that aren't marked by an `await` (the "suspend" parts are the interleaving points), as well as many delegates including myself objecting to ever having the mere mention of a variable cause side effects (modulo `with` and global accessors, ofc, which sadly we can't remove)
